name: Build & Release
on:
  pull_request:
    branches:
      - main


jobs:
  flutter_build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chechout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_build]
    runs-on: macos-latest
    steps:
      - uses: actions/chechout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios
  

  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chechout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle
